/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./admin.html",
    "./vendor.html",
    "./client/**/*.{js,ts,jsx,tsx}",
    "./admin/**/*.{js,ts,jsx,tsx}",
    "./vendor/**/*.{js,ts,jsx,tsx}",
    "./shared/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#99907c",
        "secondary-fixed": "#e5e2e1",
        "inverse-on-surface": "#343027",
        "on-tertiary-container": "#254188",
        "inverse-surface": "#eae1d4",
        "secondary": "#c8c6c5",
        "tertiary-fixed-dim": "#b4c5ff",
        "outline-variant": "#4d4635",
        "deep-charcoal": "#0A0A0A",
        "primary-fixed": "#ffe088",
        "surface": "#16130b",
        "tertiary-container": "#97b0ff",
        "background": "#16130b",
        "surface-tint": "#e9c349",
        "glass-border": "rgba(212, 175, 55, 0.2)",
        "inverse-primary": "#735c00",
        "primary-fixed-dim": "#e9c349",
        "surface-container-low": "#1f1b13",
        "secondary-container": "#474746",
        "on-primary": "#3c2f00",
        "on-secondary": "#313030",
        "on-primary-fixed-variant": "#574500",
        "surface-variant": "#38342b",
        "surface-bright": "#3d392f",
        "error": "#ffb4ab",
        "on-primary-container": "#554300",
        "surface-container-highest": "#38342b",
        "surface-container-lowest": "#110e07",
        "on-secondary-container": "#b7b5b4",
        "surface-elevated": "#1E1E1E",
        "on-background": "#eae1d4",
        "surface-container": "#231f17",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary": "#f2ca50",
        "surface-container-high": "#2d2a21",
        "on-tertiary-fixed": "#00174b",
        "on-secondary-fixed": "#1c1b1b",
        "on-secondary-fixed-variant": "#474746",
        "secondary-fixed-dim": "#c8c6c5",
        "tertiary-fixed": "#dbe1ff",
        "on-error": "#690005",
        "primary-container": "#d4af37",
        "tertiary": "#bfcdff",
        "on-surface-variant": "#d0c5af",
        "luxury-gold": "#D4AF37",
        "on-surface": "#eae1d4",
        "on-tertiary-fixed-variant": "#27438a",
        "on-tertiary": "#082b72",
        "muted-gold": "#C5A059",
        "on-primary-fixed": "#241a00",
        "surface-dim": "#16130b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "80px",
        "margin-mobile": "20px",
        "section-gap": "120px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Hanken Grotesk"],
        "label-caps": ["Inter"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "display-lg": ["64px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["12px", { "lineHeight": "1", "letterSpacing": "0.15em", "fontWeight": "700" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "headline-lg": ["40px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
